spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Damir2005
    url: jdbc:postgresql://localhost:5432/vk
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8092